### ISSUE TITLE
Partitions with ServicesApi have intermittent timeouts 

### ISSUE THREAD

**Issue by michal-harish** [amient/affinity#63]
java.util.concurrent.TimeoutException: Futures timed out after [7 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
        at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
        at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
        at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:165)
        at scala.concurrent.Await$.result(package.scala:190)
        at io.amient.affinity.core.cluster.Coordinator$$anonfun$updateGroup$1.apply(Coordinator.scala:143)
        at io.amient.affinity.core.cluster.Coordinator$$anonfun$updateGroup$1.apply(Coordinator.scala:141)
        at scala.collection.immutable.Map$Map2.foreach(Map.scala:137)
        at io.amient.affinity.core.cluster.Coordinator.updateGroup(Coordinator.scala:141)
        at io.amient.affinity.core.cluster.CoordinatorZk.io$amient$affinity$core$cluster$CoordinatorZk$$updateChildren(CoordinatorZk.scala:81)
        at io.amient.affinity.core.cluster.CoordinatorZk.<init>(CoordinatorZk.scala:61)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at io.amient.affinity.core.cluster.Coordinator$.create(Coordinator.scala:55)
        at io.amient.affinity.core.actor.ServicesApi$class.service(ServicesApi.scala:53)
        at com.trustelevate.vpc.service.ParentService.service(ParentService.scala:19)
        at com.trustelevate.vpc.service.ParentService.<init>(ParentService.scala:36)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at io.amient.affinity.core.cluster.Node$$anonfun$startContainer$1.apply(Node.scala:97)
        at io.amient.affinity.core.cluster.Node$$anonfun$startContainer$1.apply(Node.scala:97)
        at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
        at akka.actor.Props.newActor(Props.scala:213)
        at akka.actor.ActorCell.newActor(ActorCell.scala:562)
        at akka.actor.ActorCell.create(ActorCell.scala:588)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by michal-harish** [comment]
This seems to be related to competing zk-node owners because after enough timeout for zookeeper  ephemerals to disappear this problem doesn't manifest
