### ISSUE TITLE
AvroRecord.read

### ISSUE THREAD

**Issue by michal-harish** [amient/affinity#77]
schemaRegistry.getCurrentSchema(writerSchema.getFullName) match {
          case None =>

Currently the code above, returns a GenericRecord, but this is not correct behaviour. In this situation, first cache should be resynced with remote registry and if after that the schema doesn't exist  throw illegal stage exception

**Comment by michal-harish** [comment]
There seems to be some kind of out-of-sync behaviour where the class loader doesn't recognize the fully qualified name on startup, but later on it does. This still needs investigating..

**Comment by michal-harish** [comment]
e.g. 

{Code}
Unsupported Avro Case Class type com.*****.CredentialIndex
        at io.amient.affinity.avro.AvroRecord$.inferSchema(AvroRecord.scala:338)
        at io.amient.affinity.avro.AvroRecord.<init>(AvroRecord.scala:349)
        at com.*****.CredentialIndex.<init>(***.scala:20)
{Code}
