### ISSUE TITLE
Weird scala type reflection behaviour!!

### ISSUE THREAD

**Issue by michal-harish** [amient/affinity#85]
on few occasions i've seen the following error which is thrown by AvroRecord.read if it doesn't resognise the type as <:< typeOf[AvroRecord[_]]. The types for which it happened were all declared as extending AvroRecord however so it doesn't make much sense.

{Code}
Unsupported Avro Case Class type com..CredentialIndex
at io.amient.affinity.avro.AvroRecord$.inferSchema(AvroRecord.scala:338)
at io.amient.affinity.avro.AvroRecord.(AvroRecord.scala:349)
at com..CredentialIndex.(***.scala:20)
{Code}

**Comment by michal-harish** [comment]
Similar but different:
```
Caused by: java.lang.IllegalArgumentException: Unsupported Avro Case Class type Option[String]
	at io.amient.affinity.avro.AvroRecord$$anonfun$inferSchema$2.apply(AvroRecord.scala:419)
	at io.amient.affinity.avro.AvroRecord$$anonfun$inferSchema$2.apply(AvroRecord.scala:366)
	at io.amient.affinity.avro.AvroRecord$LocalCache.getOrInitialize(AvroRecord.scala:171)
	at io.amient.affinity.avro.AvroRecord$.inferSchema(AvroRecord.scala:365)
	at io.amient.affinity.avro.AvroRecord$$anonfun$inferSchema$2$$anonfun$5.apply(AvroRecord.scala:407)
	at io.amient.affinity.avro.AvroRecord$$anonfun$inferSchema$2$$anonfun$5.apply(AvroRecord.scala:405)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at io.amient.affinity.avro.AvroRecord$$anonfun$inferSchema$2.apply(AvroRecord.scala:405)
	at io.amient.affinity.avro.AvroRecord$$anonfun$inferSchema$2.apply(AvroRecord.scala:366)
	at io.amient.affinity.avro.AvroRecord$LocalCache.getOrInitialize(AvroRecord.scala:171)
	at io.amient.affinity.avro.AvroRecord$.inferSchema(AvroRecord.scala:365)
	at io.amient.affinity.avro.AvroRecord$.inferSchema(AvroRecord.scala:337)
	at io.amient.affinity.avro.schema.AvroSchemaProvider$$anonfun$initialize$1$$anonfun$apply$8.apply(AvroSchemaProvider.scala:143)
	at io.amient.affinity.avro.schema.AvroSchemaProvider$$anonfun$initialize$1$$anonfun$apply$8.apply(AvroSchemaProvider.scala:141)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:316)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
	at io.amient.affinity.avro.schema.AvroSchemaProvider$$anonfun$initialize$1.apply(AvroSchemaProvider.scala:141)
	at io.amient.affinity.avro.schema.AvroSchemaProvider$$anonfun$initialize$1.apply(AvroSchemaProvider.scala:105)
	at io.amient.affinity.avro.schema.CfAvroSchemaRegistry.hypersynchronized(CfAvroSchemaRegistry.scala:173)
	at io.amient.affinity.avro.schema.AvroSchemaProvider$class.initialize(AvroSchemaProvider.scala:105)
	at io.amient.affinity.avro.schema.AvroSchemaProvider$class.initialize(AvroSchemaProvider.scala:101)
	at io.amient.affinity.avro.schema.CfAvroSchemaRegistry.initialize(CfAvroSchemaRegistry.scala:58)
	at io.amient.affinity.avro.AvroSerde$.create(AvroSerde.scala:56)
	at io.amient.affinity.avro.AvroSerde$.create(AvroSerde.scala:47)
	at io.amient.affinity.core.serde.avro.AvroSerdeProxy.<init>(AvroSerdeProxy.scala:16)

```

**Comment by michal-harish** [comment]
The same thing was also observed not just on startup but during a random rest request:

```
java.lang.IllegalArgumentException: Unsupported Avro Case Class type Option[String]
	at io.amient.affinity.avro.AvroRecord$$anonfun$inferSchema$2.apply(AvroRecord.scala:419)
	at io.amient.affinity.avro.AvroRecord$$anonfun$inferSchema$2.apply(AvroRecord.scala:366)
	at io.amient.affinity.avro.AvroRecord$LocalCache.getOrInitialize(AvroRecord.scala:171)
	at io.amient.affinity.avro.AvroRecord$.inferSchema(AvroRecord.scala:365)
	at io.amient.affinity.avro.AvroRecord$$anonfun$inferSchema$2$$anonfun$5.apply(AvroRecord.scala:407)
	at io.amient.affinity.avro.AvroRecord$$anonfun$inferSchema$2$$anonfun$5.apply(AvroRecord.scala:405)
...
```
