### ISSUE TITLE
RegionSpec fails intermittently 

### ISSUE THREAD

**Issue by michal-harish** [amient/affinity#91]
When it is run alone it behaves well, but as part of the whole suite it sometimes fails:

```
- must must keep Coordinator Updated during partition failure & restart scenario *** FAILED ***
  java.lang.AssertionError: assertion failed: timeout 6 seconds expired:
  at scala.Predef$.assert(Predef.scala:170)
  at akka.testkit.TestKitBase$class.poll$1(TestKit.scala:276)
  at akka.testkit.TestKitBase$class.awaitCond(TestKit.scala:282)
  at akka.testkit.TestKit.awaitCond(TestKit.scala:814)
  at io.amient.affinity.core.actor.RegionSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(RegionSpec.scala:72)
  at io.amient.affinity.core.actor.RegionSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RegionSpec.scala:46)
  at io.amient.affinity.core.actor.RegionSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RegionSpec.scala:46)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)

```

**Comment by michal-harish** [comment]
This may have been caused by a flaky mechanism for registering gateways that do not have http interface which was already fixed so if this issue stops occurring close it.

**Comment by michal-harish** [comment]
Seems to have been fixed by the shutdown procedure cleanup.
